### ISSUE TITLE
ImportError: no module named 'itertools'

### ISSUE THREAD

**Issue by kitplummer** [Azure/iot-central-micropython-client#2]
```
Installing to: /lib/
Warning: micropython.org SSL certificate is not validated
Installing micropython-iotc 1.1.0 from https://files.pythonhosted.org/packages/f9/2a/bc30d6ee3665ea68690695aee0e15118203a1643fc3fc180be7b72f893b5/micropython-iotc-1.1.0.tar.gz
Traceback (most recent call last):
  File "<stdin>", line 12, in <module>
  File "/lib/iotc/__init__.py", line 1, in <module>
  File "/lib/iotc/constants.py", line 1, in <module>
ImportError: no module named 'itertools'
```

Maybe something I'm missing from the base image?

**Comment by kitplummer** [comment]
Urgh.  Just had to also install `itertools`.
